version: 0.1
phases:
  install:
    commands:
      - npm install time
      - aws cloudformation package --template-file samTemplate.yml --s3-bucket $S3_BUCKET --output-template-file outputSamTemplate.yml
artifacts:
  type: zip
  files:
    - outputSamTemplate.yml
